// The complete Dosa Hut menu, transcribed from the restaurant's own dataset.
// This is the authoritative source for search and the Craving Finder.
//
// It stays complete on purpose: dishes the front end should not show are
// marked `hidden` rather than deleted, so the record of what the kitchen
// actually sells survives here even while the card is off the site. Read
// VISIBLE_MENU_ITEMS, never MENU_ITEMS, when rendering.
//
// `is_veg` drives the green/red badge and is never inferred — it is taken
// verbatim from the dataset.

export type SpiceLevel = "mild" | "medium" | "spicy";

export type MenuItem = {
  code: string;
  name: string;
  category: string;
  price: string;
  is_veg: boolean;
  spice_level: SpiceLevel;
  dietary_tags: string[];
  description: string;
  /**
   * Path under /public. Absent when the kitchen has no photo of that dish yet —
   * the card renders its maroon gradient fallback rather than borrowing another
   * dish's picture, which would misrepresent what arrives at the table.
   */
  image?: string;
  /**
   * Keeps the dish out of the Craving Finder and search without deleting it.
   * Currently set on the ten dishes with no photograph: a card with the
   * gradient plate was judged worse than no card at all. Delete the flag the
   * moment a photo lands — the dish is otherwise ready to show.
   */
  hidden?: boolean;
};

export const MENU_ITEMS: MenuItem[] = [
  {
    code: "A1",
    name: "Samosa",
    category: "Snacks & Street Chaats",
    price: "$4.50 (1 Pc) / $6.95 (2 Pc)",
    is_veg: true,
    spice_level: "mild",
    dietary_tags: ["vegetarian", "starter", "snack", "fried"],
    description: "A deep fried pastry filled with potatoes & peas served with tamarind chutney",
    image: "/images/dishes/samosa.jpg",
  },
  {
    code: "A2",
    name: "Sambar Samosa (1 Pc)",
    category: "Snacks & Street Chaats",
    price: "$5.00",
    is_veg: true,
    spice_level: "mild",
    dietary_tags: ["vegetarian", "starter", "snack", "sambar"],
    description: "A deep fried pastry filled with potatoes & peas served & dipped with sambar",
    image: "/images/dishes/sambar-samosa-1-pc.jpg",
  },
  {
    code: "A3",
    name: "Vada (1 Pc)",
    category: "Snacks & Street Chaats",
    price: "$5.00",
    is_veg: true,
    spice_level: "mild",
    dietary_tags: ["vegetarian", "south_indian", "snack"],
    description: "A savory fried snack made with lentil and spiced herbs & spices served with chutney & sambar",
    image: "/images/dishes/vada-1-pc.jpg",
  },
  {
    code: "A4",
    name: "Idly (2 Pcs)",
    category: "Snacks & Street Chaats",
    price: "$9.95",
    is_veg: true,
    spice_level: "mild",
    dietary_tags: ["vegetarian", "south_indian", "steamed", "healthy"],
    description: "A soft steamed rice cake made from a fermented batter served with chutney & sambar",
    image: "/images/dishes/idly-2-pcs.jpg",
  },
  {
    code: "A5",
    name: "Idly (1 Pc) + Vada (1 Pc)",
    category: "Snacks & Street Chaats",
    price: "$10.50",
    is_veg: true,
    spice_level: "mild",
    dietary_tags: ["vegetarian", "south_indian", "combo"],
    description: "Served with chutney & sambar",
    image: "/images/dishes/idly-and-vada.jpg",
  },
  {
    code: "A6",
    name: "Ghee Podi Idly (2 Pcs)",
    category: "Snacks & Street Chaats",
    price: "$9.50",
    is_veg: true,
    spice_level: "medium",
    dietary_tags: ["vegetarian", "south_indian", "ghee", "gunpowder"],
    description: "A soft steamed rice cake made from a fermented batter spread with ghee & gunpowder (spiced lentil powder)",
    image: "/images/dishes/ghee-podi-idly-2-pcs.jpg",
  },
  {
    code: "A7",
    name: "Mirchi Bhaji (3 Pc)",
    category: "Snacks & Street Chaats",
    price: "$11.95",
    is_veg: true,
    spice_level: "spicy",
    dietary_tags: ["vegetarian", "spicy", "snack", "fried"],
    description: "Deep fried green chilli fritters",
    image: "/images/dishes/mirchi-bhaji-3-pc.jpg",
  },
  {
    code: "A8",
    name: "Cut Mirchi",
    category: "Snacks & Street Chaats",
    price: "$11.95",
    is_veg: true,
    spice_level: "spicy",
    dietary_tags: ["vegetarian", "spicy", "snack", "crispy"],
    description: "Crispy cut fried chilli fritters",
    image: "/images/dishes/cut-mirchi.jpg",
  },
  {
    code: "A9",
    name: "Bread Pakora (1 Pc)",
    category: "Snacks & Street Chaats",
    price: "$5.00",
    is_veg: true,
    spice_level: "mild",
    dietary_tags: ["vegetarian", "snack", "potato", "street_food"],
    description: "Deep fried bread stuffed with spiced potato",
    hidden: true,
  },
  {
    code: "A10",
    name: "Aaloo Bonda (2 Pc)",
    category: "Snacks & Street Chaats",
    price: "$6.95",
    is_veg: true,
    spice_level: "medium",
    dietary_tags: ["vegetarian", "potato", "snack"],
    description: "Spiced potato balls deep fried in gram flour batter",
    hidden: true,
  },
  {
    code: "C1",
    name: "Dahi Bhalla",
    category: "Snacks & Street Chaats",
    price: "$11.50",
    is_veg: true,
    spice_level: "mild",
    dietary_tags: ["vegetarian", "chaat", "yogurt", "tangy"],
    description: "Soft lentil fritters soaked in creamy yoghurt topped with tangy tamarind sauce & garnished with sev, onions, beetroot & carrot, coriander",
    image: "/images/dishes/dahi-bhalla.jpg",
  },
  {
    code: "C2",
    name: "Pani Puri (6 Pcs)",
    category: "Snacks & Street Chaats",
    price: "$10.95",
    is_veg: true,
    spice_level: "medium",
    dietary_tags: ["vegetarian", "chaat", "street_food", "tangy"],
    description: "A crispy hollow puri filled with spicy, tangy flavoured water & stuffed with potato, chana mix",
    image: "/images/dishes/pani-puri-6-pcs.jpg",
  },
  {
    code: "C3",
    name: "Dahi Puri (6 Pcs)",
    category: "Snacks & Street Chaats",
    price: "$11.50",
    is_veg: true,
    spice_level: "mild",
    dietary_tags: ["vegetarian", "chaat", "yogurt", "sweet_tangy"],
    description: "A crispy hollow puri filled with stuffed potato, chana mix & sweet yoghurt, mint sauce",
    image: "/images/dishes/dahi-puri-6-pcs.jpg",
  },
  {
    code: "C4",
    name: "Samosa Chaat",
    category: "Snacks & Street Chaats",
    price: "$11.50",
    is_veg: true,
    spice_level: "medium",
    dietary_tags: ["vegetarian", "chaat", "samosa", "street_food"],
    description: "A flavorful Indian snack made by topping crumbled samosas with chickpeas, yoghurt, chutneys, & spices",
    image: "/images/dishes/samosa-chaat.jpg",
  },
  {
    code: "C5",
    name: "Papdi Chaat",
    category: "Snacks & Street Chaats",
    price: "$11.50",
    is_veg: true,
    spice_level: "mild",
    dietary_tags: ["vegetarian", "chaat", "crispy", "street_food"],
    description: "Crispy wafers topped with boiled potatoes, chickpeas, yoghurt, chutneys, & spices, garnished with sev, onions, beetroot & carrot, coriander",
    image: "/images/dishes/papdi-chaat.jpg",
  },
  {
    code: "C6",
    name: "Pav Bhaji",
    category: "Snacks & Street Chaats",
    price: "$14.50",
    is_veg: true,
    spice_level: "medium",
    dietary_tags: ["vegetarian", "mumbai_special", "butter", "curry"],
    description: "Spicy mashed vegetable curry served with buttered, toasted buns",
    image: "/images/dishes/pav-bhaji.jpg",
  },
  {
    code: "C7",
    name: "Chole Bhature",
    category: "Snacks & Street Chaats",
    price: "$16.95",
    is_veg: true,
    spice_level: "medium",
    dietary_tags: ["vegetarian", "north_indian", "chickpeas", "heavy"],
    description: "Spicy chickpea curry (chole) served with deep-fried bread (bhature)",
    image: "/images/dishes/chole-bhature.jpg",
  },
  {
    code: "D2",
    name: "Paneer Tikka",
    category: "Tandoori Starters",
    price: "$16.95",
    is_veg: true,
    spice_level: "medium",
    dietary_tags: ["vegetarian", "paneer", "tandoori", "starter", "grilled"],
    description: "Indian marinated cottage cheese cubes, cooked in tandoor with aromatic spices & yoghurt",
    image: "/images/tandoor_starters_images/Paneer_Tikka_1.jpg",
  },
  {
    code: "D3",
    name: "Tandoori Soya Chaap",
    category: "Tandoori Starters",
    price: "$16.95",
    is_veg: true,
    spice_level: "medium",
    dietary_tags: ["vegetarian", "soya", "tandoori", "starter", "high_protein"],
    description: "Flavorful marinated soya protein, seasoned with aromatic spices & cooked in tandoor served with mint chutney",
    image: "/images/tandoor_starters_images/Tandoor_Soya_Chaap_2.jpg",
  },
  {
    code: "D4",
    name: "Soya Chaap Malai Tikka",
    category: "Tandoori Starters",
    price: "$16.95",
    is_veg: true,
    spice_level: "mild",
    dietary_tags: ["vegetarian", "soya", "creamy", "malai", "starter"],
    description: "Creamy, succulent Indian appetizer made from marinated soya protein, & aromatic spices & coated with malai cooked in tandoor served with mint chutney",
    image: "/images/tandoor_starters_images/Soya_Chaap_Malai_Tikka_3.jpg",
  },
  {
    code: "D5",
    name: "Chatpata Soya",
    category: "Tandoori Starters",
    price: "$16.95",
    is_veg: true,
    spice_level: "medium",
    dietary_tags: ["vegetarian", "soya", "tangy", "garlic", "starter"],
    description: "Spicy and tangy Indian snack made with seasoned soya chunks tossed with garlic aioli & served with mint chutney",
    image: "/images/tandoor_starters_images/Chatpat_Soya_4.jpg",
  },
  {
    code: "E1",
    name: "Dal Tadka",
    category: "Vegetarian Curries",
    price: "$19.95",
    is_veg: true,
    spice_level: "medium",
    dietary_tags: ["vegetarian", "dal", "curry", "comfort_food", "ghee"],
    description: "Traditional dal cooked lentils tempered with a flavorful blend of spices, garlic, & ghee",
    image: "/images/curry_images/Dal_Tadka_(V)_26.jpg",
  },
  {
    code: "E2",
    name: "Dal Makhani",
    category: "Vegetarian Curries",
    price: "$19.95",
    is_veg: true,
    spice_level: "mild",
    dietary_tags: ["vegetarian", "dal", "creamy", "rich", "curry"],
    description: "Rich & creamy north Indian dish made from whole black lentils & kidney beans, simmered with butter, cream, & spices",
    image: "/images/curry_images/Dal_Makhani_(V)_27.jpg",
  },
  {
    code: "E3",
    name: "Soya Chaap Tikka Masala",
    category: "Vegetarian Curries",
    price: "$18.50",
    is_veg: true,
    spice_level: "medium",
    dietary_tags: ["vegetarian", "soya", "curry", "gravy"],
    description: "Marinated and grilled soya chaap pieces cooked in a rich, creamy, & spiced tomato-based gravy",
    image: "/images/curry_images/Soya_Chaap_Tikka_Masala_(V)_28.jpg",
  },
  {
    code: "E4",
    name: "Paneer Tikka Masala",
    category: "Vegetarian Curries",
    price: "$19.95",
    is_veg: true,
    spice_level: "medium",
    dietary_tags: ["vegetarian", "paneer", "curry", "creamy", "gravy"],
    description: "Clay oven marinated & grilled paneer cubes simmered in a rich, creamy, & spiced tomato based gravy",
    image: "/images/curry_images/Paneer_Tikka_Masala_(V)_29.jpg",
  },
  {
    code: "E5",
    name: "Paneer Butter Masala",
    category: "Vegetarian Curries",
    price: "$19.95",
    is_veg: true,
    spice_level: "mild",
    dietary_tags: ["vegetarian", "paneer", "butter", "creamy", "curry"],
    description: "Creamy and mildly spiced soft paneer cubes cooked in a rich tomato-based gravy with butter & cream",
    image: "/images/curry_images/Paneer_Butter_Masala_(V)_30.jpg",
  },
  {
    code: "E6",
    name: "Palak Paneer",
    category: "Vegetarian Curries",
    price: "$19.95",
    is_veg: true,
    spice_level: "mild",
    dietary_tags: ["vegetarian", "paneer", "spinach", "healthy", "curry"],
    description: "Soft paneer cubes simmered in a creamy, spiced spinach (palak) gravy",
    image: "/images/curry_images/Palak_Paneer_(V)_31.jpg",
  },
  {
    code: "E7",
    name: "Paneer Pudina Kali Mirch",
    category: "Vegetarian Curries",
    price: "$19.95",
    is_veg: true,
    spice_level: "medium",
    dietary_tags: ["vegetarian", "paneer", "mint", "black_pepper", "curry"],
    description: "Fragrant Indian dish with paneer cubes cooked in a refreshing mint & black pepper spiced gravy",
    image: "/images/curry_images/Paneer_Pudina_Kali_Mirch_(V)_32.jpg",
  },
  {
    code: "E10",
    name: "Kadai Paneer",
    category: "Vegetarian Curries",
    price: "$19.95",
    is_veg: true,
    spice_level: "spicy",
    dietary_tags: ["vegetarian", "paneer", "spicy", "capsicum", "curry"],
    description: "Paneer cubes, bell peppers, & onions cooked in a spicy tomato-based gravy, seasoned with freshly ground spices",
    image: "/images/curry_images/Kadai_Paneer_(V)_33.jpg",
  },
  {
    code: "E11",
    name: "Veg Kolhapuri",
    category: "Vegetarian Curries",
    price: "$19.95",
    is_veg: true,
    spice_level: "spicy",
    dietary_tags: ["vegetarian", "spicy", "mixed_veg", "kolhapuri", "curry"],
    description: "Spicy and flavorful mixed vegetable curry from Kolhapur, Maharashtra, made with OTM gravy & aromatic spices",
    image: "/images/curry_images/Vegetable_Kohlapuri_(V)_34.jpg",
  },
  {
    code: "E14",
    name: "Paneer Dhaniya Hara Pyaaz",
    category: "Vegetarian Curries",
    price: "$19.95",
    is_veg: true,
    spice_level: "medium",
    dietary_tags: ["vegetarian", "paneer", "coriander", "spring_onion", "curry"],
    description: "Paneer cubes cooked with fresh coriander onions in a savory, aromatic sauce",
    image: "/images/curry_images/Paneer_Dhaniya_Hara_Pyaaz_(V)_35.jpg",
  },
  {
    code: "F1",
    name: "Vegetarian Manchuria (Dry/Gravy)",
    category: "Indo Chinese",
    price: "$18.95",
    is_veg: true,
    spice_level: "medium",
    dietary_tags: ["vegetarian", "indo_chinese", "manchurian", "starter"],
    description: "Deep-fried vegetable balls tossed in a tangy & spicy sauce",
    image: "/images/indo_chinese_images/Vegetarian_Manchuria_(V)_1.jpg",
  },
  {
    code: "F2",
    name: "Gobi Manchuria (Dry/Gravy)",
    category: "Indo Chinese",
    price: "$18.95",
    is_veg: true,
    spice_level: "medium",
    dietary_tags: ["vegetarian", "indo_chinese", "cauliflower", "manchurian"],
    description: "Crispy fried cauliflower florets tossed in a tangy and spicy sauce",
    image: "/images/indo_chinese_images/Gobi_Manchuria_(V)_2.jpg",
  },
  {
    code: "F4",
    name: "Gobi 65 (Dry/Gravy)",
    category: "Indo Chinese",
    price: "$18.95",
    is_veg: true,
    spice_level: "spicy",
    dietary_tags: ["vegetarian", "indo_chinese", "cauliflower", "spicy", "65"],
    description: "South Indian appetizer consisting of deep-fried cauliflower florets marinated in a spiced batter",
    image: "/images/indo_chinese_images/Gobi_65_(V)_3.jpg",
  },
  {
    code: "F5",
    name: "Paneer 65 (Dry/Gravy)",
    category: "Indo Chinese",
    price: "$18.95",
    is_veg: true,
    spice_level: "spicy",
    dietary_tags: ["vegetarian", "indo_chinese", "paneer", "spicy", "65"],
    description: "Spicy & crispy South Indian appetizer made with marinated & deep-fried paneer cubes",
    image: "/images/indo_chinese_images/Paneer_65_(V)_4.jpg",
  },
  {
    code: "F6",
    name: "Schezwan Paneer (Dry/Gravy)",
    category: "Indo Chinese",
    price: "$18.95",
    is_veg: true,
    spice_level: "spicy",
    dietary_tags: ["vegetarian", "indo_chinese", "paneer", "schezwan", "spicy"],
    description: "Paneer pieces stir-fried with schezwan sauce",
    hidden: true,
  },
  {
    code: "F7",
    name: "Chilli Gobi (Dry/Gravy)",
    category: "Indo Chinese",
    price: "$18.95",
    is_veg: true,
    spice_level: "spicy",
    dietary_tags: ["vegetarian", "indo_chinese", "cauliflower", "chilli", "spicy"],
    description: "Crispy fried cauliflower florets tossed in a spicy, tangy sauce with bell peppers and onions",
    image: "/images/indo_chinese_images/Chilli_Gobi_(V)_5.jpg",
  },
  {
    code: "F8",
    name: "Chilli Paneer (Dry/Gravy)",
    category: "Indo Chinese",
    price: "$18.95",
    is_veg: true,
    spice_level: "spicy",
    dietary_tags: ["vegetarian", "indo_chinese", "paneer", "chilli", "spicy"],
    description: "Paneer cubes stir-fried with bell peppers & onions in a spicy, tangy sauce",
    image: "/images/indo_chinese_images/Chilli_Paneer_(V)_6.jpg",
  },
  {
    code: "F9",
    name: "Chilli Idly",
    category: "Indo Chinese",
    price: "$18.95",
    is_veg: true,
    spice_level: "spicy",
    dietary_tags: ["vegetarian", "indo_chinese", "fusion", "idly", "spicy"],
    description: "Fried idly pieces tossed in a spicy, tangy sauce with bell peppers and onions",
    image: "/images/indo_chinese_images/Chilli_Idly_(V)_7.jpg",
  },
  {
    code: "F19",
    name: "Vegetable Noodles",
    category: "Noodles & Fried Rice",
    price: "$18.95",
    is_veg: true,
    spice_level: "mild",
    dietary_tags: ["vegetarian", "noodles", "chinese", "veg"],
    description: "Stir-fried noodles & a colorful mix of fresh vegetables, seasoned with savory sauces",
    image: "/images/dishes/vegetable-noodles.jpg",
  },
  {
    code: "F24",
    name: "Vegetarian Fried Rice",
    category: "Noodles & Fried Rice",
    price: "$18.95",
    is_veg: true,
    spice_level: "mild",
    dietary_tags: ["vegetarian", "fried_rice", "chinese", "veg"],
    description: "Stir-frying cooked rice with assorted vegetables",
    image: "/images/dishes/vegetarian-fried-rice.jpg",
  },
  {
    code: "F27",
    name: "Gobi 65 Fried Rice",
    category: "Noodles & Fried Rice",
    price: "$20.95",
    is_veg: true,
    spice_level: "spicy",
    dietary_tags: ["vegetarian", "fried_rice", "cauliflower", "spicy", "fusion"],
    description: "Spicy, deep-fried cauliflower (Gobi 65) mixed with flavorful, aromatic fried rice",
    image: "/images/dishes/gobi-65-fried-rice.jpg",
  },
  {
    code: "F30",
    name: "Triple Schezwan Fried Rice (Veg)",
    category: "Noodles & Fried Rice",
    price: "$25.95",
    is_veg: true,
    spice_level: "spicy",
    dietary_tags: ["vegetarian", "fried_rice", "noodles", "schezwan", "spicy", "combo"],
    description: "Rice, noodles, and crispy vegetables tossed in a fiery Schezwan sauce",
    image: "/images/dishes/triple-schezwan-veg-fried-rice.jpg",
  },
  {
    code: "H1",
    name: "Vegetarian Dum Biryani",
    category: "Biryani & More",
    price: "$16.95",
    is_veg: true,
    spice_level: "medium",
    dietary_tags: ["vegetarian", "biryani", "rice", "hyderabadi"],
    description: "Assorted vegetables, aromatic spices, & long-grain basmati rice, served with mirchi ka salan & raita",
    image: "/images/biryani_images/Vegetarian_Dum_Biryani_(V)_1.jpg",
  },
  {
    code: "H3",
    name: "Gobi 65 Biryani",
    category: "Biryani & More",
    price: "$17.95",
    is_veg: true,
    spice_level: "spicy",
    dietary_tags: ["vegetarian", "biryani", "cauliflower", "spicy", "fusion"],
    description: "Fusion dish combining flavorful biryani rice with spicy, deep-fried cauliflower florets",
    image: "/images/biryani_images/Gobi_65_Biryani_(V)_2.jpg",
  },
  {
    code: "H4",
    name: "Soya Chaap Tikka Biryani",
    category: "Biryani & More",
    price: "$17.95",
    is_veg: true,
    spice_level: "medium",
    dietary_tags: ["vegetarian", "biryani", "soya", "tandoori"],
    description: "Marinated soya chaap grilled to perfection, layered with fragrant rice, served with mirchi ka salan & raita",
    image: "/images/biryani_images/Soya_Chaap_Tikka_Biryani_(V)_3.jpg",
  },
  {
    code: "H5",
    name: "Paneer 65 Biryani",
    category: "Biryani & More",
    price: "$19.95",
    is_veg: true,
    spice_level: "spicy",
    dietary_tags: ["vegetarian", "biryani", "paneer", "spicy"],
    description: "Spicy flavors of Paneer 65 with fragrant basmati rice, served with mirchi ka salan and raita",
    image: "/images/biryani_images/Paneer_65_Biryani_(V)_4.jpg",
  },
  {
    code: "H6",
    name: "Paneer Tikka Biryani",
    category: "Biryani & More",
    price: "$19.95",
    is_veg: true,
    spice_level: "medium",
    dietary_tags: ["vegetarian", "biryani", "paneer", "tandoori"],
    description: "Succulent paneer cubes cooked with aromatic spices and long-grain basmati rice, served with mirchi ka salan and raita",
    image: "/images/biryani_images/Paneer_Tikka_Biryani_(V)_5.jpg",
  },
  {
    code: "I1",
    name: "Plain Dosa",
    category: "Dosa",
    price: "$8.95",
    is_veg: true,
    spice_level: "mild",
    dietary_tags: ["vegetarian", "dosa", "south_indian", "crispy"],
    description: "Crisp & golden brown crepe served with chutney & sambar",
    image: "/images/dishes/plain-dosa.jpg",
  },
  {
    code: "I2",
    name: "Onion Dosa",
    category: "Dosa",
    price: "$10.95",
    is_veg: true,
    spice_level: "mild",
    dietary_tags: ["vegetarian", "dosa", "south_indian", "onion"],
    description: "Crepe topped with onions served with chutney & sambar",
    image: "/images/dosa_images/Onion_Dosa_2.jpg",
  },
  {
    code: "I3",
    name: "Masala Dosa",
    category: "Dosa",
    price: "$15.95",
    is_veg: true,
    spice_level: "medium",
    dietary_tags: ["vegetarian", "dosa", "potato", "classic", "south_indian"],
    description: "Crepe topped with aloo masala served with chutney and sambar",
    image: "/images/dosa_images/Masala_Dosa_3.jpg",
  },
  {
    code: "I4",
    name: "Paper Dosa",
    category: "Dosa",
    price: "$8.95",
    is_veg: true,
    spice_level: "mild",
    dietary_tags: ["vegetarian", "dosa", "thin", "crispy"],
    description: "Fine crisp golden brown crepe served with chutney and sambar",
    image: "/images/dosa_images/Paper_Dosa_4.jpg",
  },
  {
    code: "I5",
    name: "Ghee Plain Dosa",
    category: "Dosa",
    price: "$9.95",
    is_veg: true,
    spice_level: "mild",
    dietary_tags: ["vegetarian", "dosa", "ghee", "south_indian"],
    description: "Crepe topped with ghee served with chutney & sambar",
    image: "/images/dosa_images/Ghee_Plain_Dosa_5.jpg",
  },
  {
    code: "I6",
    name: "Ghee Podi Dosa",
    category: "Dosa",
    price: "$9.95",
    is_veg: true,
    spice_level: "medium",
    dietary_tags: ["vegetarian", "dosa", "ghee", "gunpowder", "spicy"],
    description: "Crepe topped with ghee & gunpowder (spiced lentil powder) served with chutney & sambar",
    image: "/images/dosa_images/Ghee_Podi_Dosa_6.jpg",
  },
  {
    code: "I7",
    name: "Paneer Dosa",
    category: "Dosa",
    price: "$16.95",
    is_veg: true,
    spice_level: "medium",
    dietary_tags: ["vegetarian", "dosa", "paneer", "south_indian"],
    description: "Crepe spread with mixture of spiced cottage cheese served with chutney & sambar",
    image: "/images/dosa_images/Paneer_Dosa_7.jpg",
  },
  {
    code: "I8",
    name: "Mysore Masala Dosa",
    category: "Dosa",
    price: "$15.95",
    is_veg: true,
    spice_level: "spicy",
    dietary_tags: ["vegetarian", "dosa", "mysore", "spicy_chutney", "potato"],
    description: "Filled with spicy red chutney & potato filling, topped with gunpowder",
    hidden: true,
  },
  {
    code: "I9",
    name: "Cheese & Chilli Dosa",
    category: "Dosa",
    price: "$15.95",
    is_veg: true,
    spice_level: "spicy",
    dietary_tags: ["vegetarian", "dosa", "cheese", "chilli", "spicy"],
    description: "Filled with cheese topped with chopped chilli served with chutney and sambar",
    image: "/images/dosa_images/Cheese_and_Chilli_Dosa_8.jpg",
  },
  {
    code: "I13",
    name: "Veg Dosa Chef Special",
    category: "Dosa",
    price: "$17.95",
    is_veg: true,
    spice_level: "spicy",
    dietary_tags: ["vegetarian", "dosa", "paneer", "potato", "special"],
    description: "Combination of spicy minced paneer & aloo masala",
    image: "/images/dosa_images/Vegetable_Dosa_(V)_12.jpg",
  },
  {
    code: "I15",
    name: "Rava Plain Dosa",
    category: "Dosa",
    price: "$15.95",
    is_veg: true,
    spice_level: "mild",
    dietary_tags: ["vegetarian", "rava_dosa", "crispy", "semolina"],
    description: "Thin, crispy crepe made with semolina rice flour served with chutney & sambar",
    image: "/images/dosa_images/Rava_Plain_Dosa_14.jpg",
  },
  {
    code: "I16",
    name: "Rava Onion Dosa",
    category: "Dosa",
    price: "$16.95",
    is_veg: true,
    spice_level: "mild",
    dietary_tags: ["vegetarian", "rava_dosa", "onion", "crispy"],
    description: "Thin, crispy semolina crepe topped with onions served with chutney & sambar",
    image: "/images/dosa_images/Rava_Onion_Dosa_15.jpg",
  },
  {
    code: "I17",
    name: "Rava Masala Dosa",
    category: "Dosa",
    price: "$16.95",
    is_veg: true,
    spice_level: "medium",
    dietary_tags: ["vegetarian", "rava_dosa", "potato", "masala"],
    description: "Semolina crepe spread with aloo masala served with chutney & sambar",
    image: "/images/dosa_images/Rava_Masala_Dosa_16.jpg",
  },
  {
    code: "I18",
    name: "Rava Paneer Dosa",
    category: "Dosa",
    price: "$17.95",
    is_veg: true,
    spice_level: "medium",
    dietary_tags: ["vegetarian", "rava_dosa", "paneer"],
    description: "Semolina crepe spread with paneer masala served with chutney & sambar",
    image: "/images/dosa_images/Rava_Paneer_Dosa_17.jpg",
  },
  {
    code: "I21",
    name: "Onion Uttapam",
    category: "Dosa & Uttapam",
    price: "$16.95",
    is_veg: true,
    spice_level: "mild",
    dietary_tags: ["vegetarian", "uttapam", "onion", "thick_pancake"],
    description: "Thick South Indian pancake topped with chopped onions",
    image: "/images/dosa_images/Onion_Uttapam_19.jpg",
  },
  {
    code: "I22",
    name: "Onion & Chilli Uttapam",
    category: "Dosa & Uttapam",
    price: "$16.95",
    is_veg: true,
    spice_level: "spicy",
    dietary_tags: ["vegetarian", "uttapam", "chilli", "cheese", "spicy"],
    description: "Thick South Indian pancake topped with chopped chilli & cheese",
    image: "/images/dosa_images/Onion_and_Chilli_Uttapam_20.jpg",
  },
  {
    code: "B1",
    name: "Onion & Chilli Omelette",
    category: "Omelette",
    price: "$7.95",
    is_veg: false,
    spice_level: "spicy",
    dietary_tags: ["non_vegetarian", "egg", "omelette", "spicy"],
    description: "Eggs mixed with chopped onions, green chilies, and spices, cooked until golden brown",
    image: "/images/dishes/onion-chilli-omelette.jpg",
  },
  {
    code: "B2",
    name: "Chicken Omelette",
    category: "Omelette",
    price: "$9.50",
    is_veg: false,
    spice_level: "medium",
    dietary_tags: ["non_vegetarian", "egg", "chicken", "omelette"],
    description: "Eggs mixed with chopped chicken, onions, green chilies, and spices",
    image: "/images/dishes/chicken-omelette.jpg",
  },
  {
    code: "D1",
    name: "Chicken Tikka",
    category: "Tandoori Starters",
    price: "$18.95",
    is_veg: false,
    spice_level: "medium",
    dietary_tags: ["non_vegetarian", "chicken", "tandoori", "starter"],
    description: "Marinated chicken cooked in tandoor with aromatic spices & yoghurt",
    image: "/images/dish-chicken-tikka.jpg",
  },
  {
    code: "D6",
    name: "Murgh Malai Reshmi Tikka",
    category: "Tandoori Starters",
    price: "$18.95",
    is_veg: false,
    spice_level: "mild",
    dietary_tags: ["non_vegetarian", "chicken", "creamy", "malai", "starter"],
    description: "Tender chicken marinated in cream, cheese, & aromatic spices, cooked in tandoor",
    hidden: true,
  },
  {
    code: "D7",
    name: "Tandoori Chicken Half",
    category: "Tandoori Starters",
    price: "$18.95",
    is_veg: false,
    spice_level: "medium",
    dietary_tags: ["non_vegetarian", "chicken", "tandoori", "bone_in"],
    description: "Tender chicken (half) marinated in yoghurt and spices, roasted in a clay oven",
    image: "/images/tandoor_starters_images/Tandoor_Chicken_5.jpg",
  },
  {
    code: "D8",
    name: "Tandoori Chicken Full",
    category: "Tandoori Starters",
    price: "$23.95",
    is_veg: false,
    spice_level: "medium",
    dietary_tags: ["non_vegetarian", "chicken", "tandoori", "full_portion"],
    description: "Tender chicken marinated in yoghurt and spices, roasted in a clay oven",
    hidden: true,
  },
  {
    code: "D9",
    name: "Seekh Kebab (Lamb)",
    category: "Tandoori Starters",
    price: "$19.95",
    is_veg: false,
    spice_level: "spicy",
    dietary_tags: ["non_vegetarian", "lamb", "kebab", "tandoori", "spicy"],
    description: "Minced lamb seasoned with aromatic spices, molded onto skewers, and clay oven cooked",
    image: "/images/tandoor_starters_images/Lamb_Seekh_Kebab_6.jpg",
  },
  {
    code: "D10",
    name: "Mixed Tandoor Platter",
    category: "Tandoori Starters",
    price: "$28.95",
    is_veg: false,
    spice_level: "medium",
    dietary_tags: ["non_vegetarian", "platter", "chicken", "lamb", "tandoori"],
    description: "Delectable mix of tandoori appetizers cooked in traditional clay oven",
    hidden: true,
  },
  {
    code: "D11",
    name: "Lamb Chop",
    category: "Tandoori Starters",
    price: "$19.95",
    is_veg: false,
    spice_level: "medium",
    dietary_tags: ["non_vegetarian", "lamb", "chops", "tandoori"],
    description: "Succulent Lamb marinated in spiced yoghurt and gently roasted in a clay oven",
    hidden: true,
  },
  {
    code: "E15",
    name: "Butter Chicken",
    category: "Chicken Curries",
    price: "$21.95",
    is_veg: false,
    spice_level: "mild",
    dietary_tags: ["non_vegetarian", "chicken", "butter_chicken", "creamy", "curry"],
    description: "Tender pieces of chicken cooked in a rich tomato-based sauce with butter, cream, & spices",
    image: "/images/curry_images/Butter_Chicken_1.jpg",
  },
  {
    code: "E16",
    name: "Punjabi Butter Chicken",
    category: "Chicken Curries",
    price: "$21.95",
    is_veg: false,
    spice_level: "medium",
    dietary_tags: ["non_vegetarian", "chicken", "bone_in", "punjabi", "curry"],
    description: "Bone chicken pieces cooked in a rich tomato sauce, flavored with butter, cream, & spices",
    // Shared a byte-identical photo with E15 Butter Chicken; hidden rather than
    // show the same picture under two names.
    hidden: true,
  },
  {
    code: "E17",
    name: "Delhi Mughlai Chicken",
    category: "Chicken Curries",
    price: "$21.95",
    is_veg: false,
    spice_level: "mild",
    dietary_tags: ["non_vegetarian", "chicken", "mughlai", "royal", "curry"],
    description: "Tender chicken cooked in a spiced yoghurt & tomato gravy",
    image: "/images/curry_images/Delhi_Mughlai_Chicken_2.jpg",
  },
  {
    code: "E18",
    name: "Murgh Pudina Kali Mirch",
    category: "Chicken Curries",
    price: "$21.95",
    is_veg: false,
    spice_level: "medium",
    dietary_tags: ["non_vegetarian", "chicken", "mint", "black_pepper", "curry"],
    description: "Chicken cooked with fresh mint leaves and black pepper in a creamy aromatic gravy",
    image: "/images/curry_images/Murgh_Pudina_Kali_Mirch_3.jpg",
  },
  {
    code: "E19",
    name: "Chicken Kolhapuri",
    category: "Chicken Curries",
    price: "$21.95",
    is_veg: false,
    spice_level: "spicy",
    dietary_tags: ["non_vegetarian", "chicken", "kolhapuri", "spicy", "curry"],
    description: "Fiery curry featuring chicken simmered in roasted spices & coconut",
    image: "/images/curry_images/Chicken_Kolhapuri_4.jpg",
  },
  {
    code: "E20",
    name: "Chicken Madras",
    category: "Chicken Curries",
    price: "$21.95",
    is_veg: false,
    spice_level: "spicy",
    dietary_tags: ["non_vegetarian", "chicken", "madras", "south_indian", "spicy"],
    description: "Spicy South Indian curry with chicken cooked in a tangy tomato sauce",
    image: "/images/curry_images/Chicken_Madras_5.jpg",
  },
  {
    code: "E21",
    name: "Chicken Tikka Masala",
    category: "Chicken Curries",
    price: "$21.95",
    is_veg: false,
    spice_level: "medium",
    dietary_tags: ["non_vegetarian", "chicken", "tikka_masala", "curry"],
    description: "Clay oven chicken cooked in a creamy tomato-based sauce with aromatic spices",
    image: "/images/curry_images/Chicken_Tikka_Masala_6.jpg",
  },
  {
    code: "E22",
    name: "Kadai Chicken",
    category: "Chicken Curries",
    price: "$21.95",
    is_veg: false,
    spice_level: "spicy",
    dietary_tags: ["non_vegetarian", "chicken", "kadai", "capsicum", "spicy"],
    description: "Chicken, bell peppers, tomatoes, & aromatic spices cooked in kadai",
    image: "/images/curry_images/Kadai_Chicken_7.jpg",
  },
  {
    code: "E27",
    name: "Adarki Rara Chicken",
    category: "Chicken Curries",
    price: "$21.95",
    is_veg: false,
    spice_level: "spicy",
    dietary_tags: ["non_vegetarian", "chicken", "keema", "ginger", "spicy"],
    description: "Rich & spicy gravy made with minced chicken & infused with ginger",
    image: "/images/curry_images/Adarki_Rara_Chicken_8.jpg",
  },
  {
    code: "E28",
    name: "Lamb Roganjosh",
    category: "Goat, Lamb & Seafood Curries",
    price: "$22.95",
    is_veg: false,
    spice_level: "medium",
    dietary_tags: ["non_vegetarian", "lamb", "rogan_josh", "kashmiri", "curry"],
    description: "Fragrant Kashmiri curry featuring tender lamb simmered in a spiced yoghurt & tomato sauce",
    image: "/images/curry_images/Lamb_Rogan_Josh_13.jpg",
  },
  {
    code: "E31",
    name: "Pepper Lamb Masala",
    category: "Goat, Lamb & Seafood Curries",
    price: "$22.95",
    is_veg: false,
    spice_level: "spicy",
    dietary_tags: ["non_vegetarian", "lamb", "black_pepper", "spicy", "curry"],
    description: "Tender lamb cooked with freshly ground black pepper & savory spices",
    image: "/images/curry_images/Pepper_Lamb_Masala_14.jpg",
  },
  {
    code: "E33",
    name: "Goat Curry",
    category: "Goat, Lamb & Seafood Curries",
    price: "$23.95",
    is_veg: false,
    spice_level: "medium",
    dietary_tags: ["non_vegetarian", "goat", "mutton", "curry"],
    description: "Tender mutton pieces simmered in a rich, spiced gravy",
    image: "/images/curry_images/Goat_Curry_19.jpg",
  },
  {
    code: "E35",
    name: "Bhuna Goat",
    category: "Goat, Lamb & Seafood Curries",
    price: "$23.95",
    is_veg: false,
    spice_level: "spicy",
    dietary_tags: ["non_vegetarian", "goat", "bhuna", "spicy", "thick_gravy"],
    description: "Tender goat meat slow-cooked with aromatic spices until sauce is thick",
    image: "/images/curry_images/Bhuna_Goat_20.jpg",
  },
  {
    code: "E37",
    name: "Delhi Mughlai Goat Curry",
    category: "Goat, Lamb & Seafood Curries",
    price: "$23.95",
    is_veg: false,
    spice_level: "mild",
    dietary_tags: ["non_vegetarian", "goat", "mughlai", "royal", "curry"],
    description: "Goat meat cooked in a creamy, spiced royal style mix",
    image: "/images/curry_images/Delhi_Mughlai_Goat_Curry_21.jpg",
  },
  {
    code: "E39",
    name: "Goat Karahi",
    category: "Goat, Lamb & Seafood Curries",
    price: "$23.95",
    is_veg: false,
    spice_level: "spicy",
    dietary_tags: ["non_vegetarian", "goat", "kadai", "spicy", "curry"],
    description: "Goat meat cooked with tomatoes, green chilies, & aromatic spices",
    image: "/images/curry_images/Goat_Karahi_22.jpg",
  },
  {
    code: "E41",
    name: "Prawn Masala",
    category: "Goat, Lamb & Seafood Curries",
    price: "$23.95",
    is_veg: false,
    spice_level: "spicy",
    dietary_tags: ["non_vegetarian", "seafood", "prawn", "spicy", "curry"],
    description: "Prawns cooked in a rich blend of aromatic spices & tomatoes",
    image: "/images/dishes/prawn-masala.jpg",
  },
  {
    code: "F12",
    name: "Chicken Manchuria (Dry/Gravy)",
    category: "Indo Chinese",
    price: "$19.95",
    is_veg: false,
    spice_level: "medium",
    dietary_tags: ["non_vegetarian", "chicken", "manchurian", "indo_chinese"],
    description: "Tender chicken pieces coated in a spicy batter & stir-fried in savory sauce",
    image: "/images/indo_chinese_images/Chicken_Manchuria_8.jpg",
  },
  {
    code: "F13",
    name: "Chicken 65 (Dry/Gravy)",
    category: "Indo Chinese",
    price: "$19.95",
    is_veg: false,
    spice_level: "spicy",
    dietary_tags: ["non_vegetarian", "chicken", "65", "spicy", "indo_chinese"],
    description: "Spicy and crispy South Indian appetizer made with deep-fried chicken",
    image: "/images/indo_chinese_images/Chicken_65_9.jpg",
  },
  {
    code: "F14",
    name: "Chilli Chicken (Dry/Gravy)",
    category: "Indo Chinese",
    price: "$19.95",
    is_veg: false,
    spice_level: "spicy",
    dietary_tags: ["non_vegetarian", "chicken", "chilli", "spicy", "indo_chinese"],
    description: "Chicken pieces stir-fried with bell peppers, onions, & a spicy, tangy sauce",
    image: "/images/indo_chinese_images/Chilli_Chicken_10.jpg",
  },
  {
    code: "F15",
    name: "Schezwan Chicken (Dry/Gravy)",
    category: "Indo Chinese",
    price: "$19.95",
    is_veg: false,
    spice_level: "spicy",
    dietary_tags: ["non_vegetarian", "chicken", "schezwan", "spicy", "indo_chinese"],
    description: "Tender chicken pieces stir-fried with schezwan sauce",
    image: "/images/indo_chinese_images/Schezwan_Chicken_11.jpg",
  },
  {
    code: "F16",
    name: "Ginger Chicken (Dry/Gravy)",
    category: "Indo Chinese",
    price: "$19.95",
    is_veg: false,
    spice_level: "medium",
    dietary_tags: ["non_vegetarian", "chicken", "ginger", "indo_chinese"],
    description: "Savory dish featuring tender chicken cooked with ginger, garlic, & spices",
    image: "/images/indo_chinese_images/Ginger_Chicken_12.jpg",
  },
  {
    code: "F17",
    name: "Crispy Goat (Dry)",
    category: "Indo Chinese",
    price: "$20.95",
    is_veg: false,
    spice_level: "medium",
    dietary_tags: ["non_vegetarian", "goat", "crispy", "starter", "indo_chinese"],
    description: "Deep fried tender goat meat tossed with aromatic spices & herbs",
    image: "/images/indo_chinese_images/Crispy_Goat_13.jpg",
  },
  {
    code: "F18",
    name: "Chilli Goat (Dry)",
    category: "Indo Chinese",
    price: "$20.95",
    is_veg: false,
    spice_level: "spicy",
    dietary_tags: ["non_vegetarian", "goat", "chilli", "spicy", "indo_chinese"],
    description: "Deep fried tender goat meat tossed with spices, herbs and chilli sauce",
    image: "/images/indo_chinese_images/Chilli_Goat_14.jpg",
  },
  {
    code: "F20",
    name: "Egg Noodles",
    category: "Noodles & Fried Rice",
    price: "$18.95",
    is_veg: false,
    spice_level: "mild",
    dietary_tags: ["non_vegetarian", "egg", "noodles", "chinese"],
    description: "Stir-fried noodles & scrambled eggs combined with vegetables",
    image: "/images/dishes/egg-noodles.jpg",
  },
  {
    code: "F21",
    name: "Chicken Noodles",
    category: "Noodles & Fried Rice",
    price: "$19.95",
    is_veg: false,
    spice_level: "mild",
    dietary_tags: ["non_vegetarian", "chicken", "noodles", "chinese"],
    description: "Stir-fried noodles with tender chicken pieces, vegetables, & seasonings",
    image: "/images/dishes/chicken-noodles.jpg",
  },
  {
    code: "F22",
    name: "Prawn Noodles",
    category: "Noodles & Fried Rice",
    price: "$21.95",
    is_veg: false,
    spice_level: "mild",
    dietary_tags: ["non_vegetarian", "seafood", "prawn", "noodles", "chinese"],
    description: "Stir-fried noodles with succulent prawns, vegetables, & seasonings",
    image: "/images/dishes/prawn-noodles.jpg",
  },
  {
    code: "F23",
    name: "Mixed Noodles",
    category: "Noodles & Fried Rice",
    price: "$21.95",
    is_veg: false,
    spice_level: "medium",
    dietary_tags: ["non_vegetarian", "chicken", "prawn", "noodles", "combo"],
    description: "Noodles with vegetables, chicken & prawns seasoned with aromatic sauces",
    image: "/images/dishes/mixed-noodles.jpg",
  },
  {
    code: "F25",
    name: "Egg Fried Rice",
    category: "Noodles & Fried Rice",
    price: "$18.95",
    is_veg: false,
    spice_level: "mild",
    dietary_tags: ["non_vegetarian", "egg", "fried_rice", "chinese"],
    description: "Scrambled eggs, vegetables, and savory seasonings with rice",
    image: "/images/dishes/egg-fried-rice.jpg",
  },
  {
    code: "F26",
    name: "Chicken Fried Rice",
    category: "Noodles & Fried Rice",
    price: "$19.95",
    is_veg: false,
    spice_level: "mild",
    dietary_tags: ["non_vegetarian", "chicken", "fried_rice", "chinese"],
    description: "Stir-frying cooked rice with tender chicken pieces & vegetables",
    image: "/images/dishes/chicken-fried-rice.jpg",
  },
  {
    code: "F28",
    name: "Mixed Fried Rice",
    category: "Noodles & Fried Rice",
    price: "$21.95",
    is_veg: false,
    spice_level: "medium",
    dietary_tags: ["non_vegetarian", "chicken", "prawn", "fried_rice", "combo"],
    description: "Fried rice with vegetables, chicken & prawns",
    image: "/images/dishes/mixed-fried-rice.jpg",
  },
  {
    code: "F29",
    name: "Chicken 65 Fried Rice",
    category: "Noodles & Fried Rice",
    price: "$20.50",
    is_veg: false,
    spice_level: "spicy",
    dietary_tags: ["non_vegetarian", "chicken", "65", "fried_rice", "spicy"],
    description: "Deep-fried Chicken 65 tossed with aromatic fried rice",
    image: "/images/dishes/chicken-65-fried-rice.jpg",
  },
  {
    code: "F31",
    name: "Triple Schezwan Fried Rice (Chicken)",
    category: "Noodles & Fried Rice",
    price: "$26.95",
    is_veg: false,
    spice_level: "spicy",
    dietary_tags: ["non_vegetarian", "chicken", "schezwan", "fried_rice", "noodles", "spicy"],
    description: "Spicy dish combining rice, noodles, and chicken in Schezwan sauce",
    image: "/images/dishes/triple-schezwan-chicken-fried-rice.jpg",
  },
  {
    code: "H9",
    name: "Egg Biryani",
    category: "Biryani & More",
    price: "$18.95",
    is_veg: false,
    spice_level: "medium",
    dietary_tags: ["non_vegetarian", "egg", "biryani", "rice"],
    description: "Boiled eggs cooked with aromatic spices and basmati rice, served with mirchi ka salan & raita",
    image: "/images/biryani_images/Egg_Biryani_6.jpg",
  },
  {
    code: "H10",
    name: "Egg 65 Biryani",
    category: "Biryani & More",
    price: "$18.95",
    is_veg: false,
    spice_level: "spicy",
    dietary_tags: ["non_vegetarian", "egg", "65", "biryani", "spicy"],
    description: "Spicy egg 65 combined with basmati rice, served with mirchi ka salan & raita",
    image: "/images/biryani_images/Egg_65_Biryani_7.jpg",
  },
  {
    code: "H11",
    name: "Chicken Dum Biryani",
    category: "Biryani & More",
    price: "$19.95",
    is_veg: false,
    spice_level: "medium",
    dietary_tags: ["non_vegetarian", "chicken", "biryani", "classic", "hyderabadi"],
    description: "Classic chicken pieces layered with basmati rice, served with mirchi ka salan & raita",
    image: "/images/dishes/chicken-dum-biryani.jpg",
  },
  {
    code: "H12",
    name: "Chicken 65 Biryani",
    category: "Biryani & More",
    price: "$19.95",
    is_veg: false,
    spice_level: "spicy",
    dietary_tags: ["non_vegetarian", "chicken", "65", "biryani", "spicy"],
    description: "Spicy chicken 65 combined with basmati rice, served with mirchi ka salan & raita",
    image: "/images/biryani_images/Chicken_65_Biryani_9.jpg",
  },
  {
    code: "H14",
    name: "Ghee Chicken Roast Biryani",
    category: "Biryani & More",
    price: "$19.95",
    is_veg: false,
    spice_level: "medium",
    dietary_tags: ["non_vegetarian", "chicken", "ghee", "roast", "biryani"],
    description: "Bone chicken pieces slow cooked in ghee layered with basmati rice",
    image: "/images/biryani_images/Ghee_Chicken_Roast_Biryani_10.jpg",
  },
  {
    code: "H15",
    name: "Chicken Tikka Biryani",
    category: "Biryani & More",
    price: "$19.95",
    is_veg: false,
    spice_level: "medium",
    dietary_tags: ["non_vegetarian", "chicken", "tikka", "biryani", "tandoori"],
    description: "Marinated chicken tikka slow cooked in ghee layered with basmati rice",
    image: "/images/biryani_images/Chicken_Tikka_Biryani_11.jpg",
  },
  {
    code: "H16",
    name: "Chicken Fry Piece Biryani",
    category: "Biryani & More",
    price: "$19.95",
    is_veg: false,
    spice_level: "spicy",
    dietary_tags: ["non_vegetarian", "chicken", "fried", "biryani", "spicy"],
    description: "Marinated chicken pieces fried to perfection and layered with basmati rice",
    image: "/images/biryani_images/Fried_Chicken_Pieces_Biryani_12.jpg",
  },
  {
    code: "H17",
    name: "Pacchi Mirchi Chicken Biryani",
    category: "Biryani & More",
    price: "$19.95",
    is_veg: false,
    spice_level: "spicy",
    dietary_tags: ["non_vegetarian", "chicken", "green_chilli", "biryani", "spicy"],
    description: "Hyderabadi-style biryani with green chilies and basmati rice",
    image: "/images/biryani_images/Pacchi_Mirchi_Chicken_Biryani_13.jpg",
  },
  {
    code: "H20",
    name: "Prawn Roast Biryani",
    category: "Biryani & More",
    price: "$21.95",
    is_veg: false,
    spice_level: "medium",
    dietary_tags: ["non_vegetarian", "seafood", "prawn", "biryani"],
    description: "Succulent prawns roasted and layered with basmati rice",
    hidden: true,
  },
  {
    code: "H21",
    name: "Special Keema Pulao",
    category: "Biryani & More",
    price: "$21.95",
    is_veg: false,
    spice_level: "medium",
    dietary_tags: ["non_vegetarian", "keema", "minced_meat", "pulao", "rice"],
    description: "Spiced minced meat cooked with aromatic basmati rice",
    image: "/images/biryani_images/Special_Keema_Pulao_14.jpg",
  },
  {
    code: "I10",
    name: "Chicken Dosa",
    category: "Dosa",
    price: "$16.95",
    is_veg: false,
    spice_level: "medium",
    dietary_tags: ["non_vegetarian", "dosa", "chicken", "minced_meat"],
    description: "Filled with marinated chicken mince & served with chutney & sambar",
    image: "/images/dosa_images/Chicken_Dosa_9.jpg",
  },
  {
    code: "I11",
    name: "Chicken 65 Dosa",
    category: "Dosa",
    price: "$16.95",
    is_veg: false,
    spice_level: "spicy",
    dietary_tags: ["non_vegetarian", "dosa", "chicken_65", "spicy"],
    description: "Combining spicy, tangy Chicken 65 with a crispy dosa",
    image: "/images/dosa_images/Chicken_65_Dosa_10.jpg",
  },
  {
    code: "I12",
    name: "Lamb Dosa",
    category: "Dosa",
    price: "$16.95",
    is_veg: false,
    spice_level: "medium",
    dietary_tags: ["non_vegetarian", "dosa", "lamb", "minced_meat"],
    description: "Filled with marinated lamb mince & served with chutney & sambar",
    image: "/images/dosa_images/Lamb_Dosa_11.jpg",
  },
  {
    code: "I14",
    name: "Non-Veg Dosa Chef Special",
    category: "Dosa",
    price: "$17.95",
    is_veg: false,
    spice_level: "spicy",
    dietary_tags: ["non_vegetarian", "dosa", "chicken", "lamb", "paneer", "special"],
    description: "Filled with spiced paneer, aloo masala, mince chicken, and mince lamb",
    image: "/images/dosa_images/Non_Vegetable_Dosa_13.jpg",
  },
  {
    code: "I19",
    name: "Rava Chicken Dosa",
    category: "Dosa",
    price: "$18.95",
    is_veg: false,
    spice_level: "medium",
    dietary_tags: ["non_vegetarian", "rava_dosa", "chicken"],
    description: "Semolina crepe spread with marinated mince chicken",
    hidden: true,
  },
  {
    code: "I20",
    name: "Rava Lamb Dosa",
    category: "Dosa",
    price: "$18.95",
    is_veg: false,
    spice_level: "medium",
    dietary_tags: ["non_vegetarian", "rava_dosa", "lamb"],
    description: "Semolina crepe spread with marinated mince lamb",
    image: "/images/dosa_images/Rava_Lamb_Dosa_18.jpg",
  },
  {
    code: "J8",
    name: "Keema Naan",
    category: "Stuffed Naan",
    price: "$5.99",
    is_veg: false,
    spice_level: "medium",
    dietary_tags: ["non_vegetarian", "naan", "bread", "keema"],
    description: "Flatbread stuffed with spiced minced meat",
    image: "/images/dishes/keema-naan.jpg",
  },
  {
    code: "J9",
    name: "Chicken Tikka Naan",
    category: "Stuffed Naan",
    price: "$5.99",
    is_veg: false,
    spice_level: "medium",
    dietary_tags: ["non_vegetarian", "naan", "bread", "chicken_tikka"],
    description: "Flatbread filled with flavorful, spiced chicken tikka",
    image: "/images/dishes/chicken-tikka-naan.jpg",
  },
];

/** Every category present in the dataset, in first-seen order. */
export const MENU_CATEGORIES: string[] = Array.from(
  new Set(MENU_ITEMS.map((item) => item.category)),
);

/**
 * What the site renders. Everything the Craving Finder and search read comes
 * from here, so hiding a dish is a one-line change in the data rather than a
 * filter repeated in each component.
 */
export const VISIBLE_MENU_ITEMS: MenuItem[] = MENU_ITEMS.filter((item) => !item.hidden);

/**
 * Free-text search across code, name, category, description and tags.
 *
 * Ranked rather than filtered flat: an exact code match comes first, then a
 * name match, then everything else, so typing "E41" or "prawn" puts the
 * obvious answer at the top instead of burying it among description hits.
 */
export function searchMenu(query: string, limit = 24): MenuItem[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const terms = q.split(/\s+/);

  const scored = VISIBLE_MENU_ITEMS.map((item) => {
    const name = item.name.toLowerCase();
    const code = item.code.toLowerCase();
    const haystack = [
      code,
      name,
      item.category.toLowerCase(),
      item.description.toLowerCase(),
      item.spice_level,
      item.dietary_tags.join(" "),
    ].join(" ");

    // Every term has to appear somewhere, so "spicy chicken" cannot match a
    // mild paneer dish on the word "chicken" alone.
    if (!terms.every((t) => haystack.includes(t))) return null;

    let score = 0;
    if (code === q) score += 100;
    else if (code.startsWith(q)) score += 60;
    if (name === q) score += 80;
    else if (name.startsWith(q)) score += 40;
    else if (name.includes(q)) score += 25;
    if (item.category.toLowerCase().includes(q)) score += 15;
    if (item.dietary_tags.some((t) => t.includes(q.replace(/\s+/g, "_")))) score += 12;
    if (item.spice_level === q) score += 10;
    return { item, score };
  }).filter(Boolean) as { item: MenuItem; score: number }[];

  return scored
    .sort((a, b) => b.score - a.score || a.item.code.localeCompare(b.item.code))
    .slice(0, limit)
    .map((s) => s.item);
}
